Repository Babywise/Restaurant-WebApp-ASP.NET, pull requests merged in 2023-04, with the labels that each got.

#2 Database
  Meal Ordering API/Entities/MealOrderingContext.cs
  Meal Ordering API/Entities/account.cs
  Meal Ordering API/Entities/category.cs
  Meal Ordering API/Entities/order.cs
  Meal Ordering API/Entities/product.cs
  Meal Ordering API/Migrations/MealOrderingContextModelSnapshot.cs
  Meal Ordering API/Migrations/accountMigration.Designer.cs
  Meal Ordering API/Migrations/accountMigration.cs
  Meal Ordering API/Migrations/categoryMigration.Designer.cs
  Meal Ordering API/Migrations/categoryMigration.cs
  Meal Ordering API/Migrations/orderMigration.Designer.cs
  Meal Ordering API/Migrations/orderMigration.cs
  Meal Ordering API/Migrations/productMigration.Designer.cs
  Meal Ordering API/Migrations/productMigration.cs
  Meal Ordering API/Program.cs
  Meal Ordering API/appsettings.json
Labels: enhancement

#1 Readme updates
  README.md
Labels: documentation

#20 Fixed session inconsistency for order tabs Closes #18
  Meal Ordering Restaurant/Controllers/OrderController.cs
Labels: bug

#24 fixed sorting of orders by status. close #22
  Meal Ordering Restaurant/Controllers/OrderController.cs
Labels: bug

#27 Account views update
  Meal Ordering Customer/Views/Account/Edit.cshtml
  Meal Ordering Customer/Views/Account/Login.cshtml
  Meal Ordering Customer/Views/Account/Register.cshtml
  Meal Ordering Customer/Views/Account/_AccountFormFieldsPartial.cshtml
  Meal Ordering Customer/Views/Account/_AccountPasswordPartial.cshtml
  Meal Ordering Restaurant/Meal Ordering Restaurant.csproj
  Meal Ordering Restaurant/Program.cs
  Meal Ordering Restaurant/Views/Account/Edit.cshtml
  Meal Ordering Restaurant/Views/Account/Login.cshtml
  Meal Ordering Restaurant/Views/Account/Register.cshtml
  Meal Ordering Restaurant/Views/Account/_AccountFormFieldsPartial.cshtml
  Meal Ordering Restaurant/Views/Account/_AccountPasswordPartial.cshtml
  Meal Ordering Restaurant/wwwroot/images/MealOrderingLogo.jpg
  Meal Ordering Restaurant/wwwroot/images/MealOrderingLogo.png
  MealOrderingApi/Migrations/20230421082513_updatelogin.Designer.cs
  MealOrderingApi/Migrations/20230421082513_updatelogin.cs
  MealOrderingApi/Properties/launchSettings.json
Labels: enhancement

#32 fixed logo image loading on page
  Meal Ordering Customer/Views/Account/Edit.cshtml
  Meal Ordering Customer/Views/Account/Login.cshtml
  Meal Ordering Customer/Views/Account/Register.cshtml
  Meal Ordering Customer/wwwroot/images/MealOrderingLogo.png
  Meal Ordering Restaurant/Views/Account/Edit.cshtml
  Meal Ordering Restaurant/Views/Account/Login.cshtml
  Meal Ordering Restaurant/Views/Account/Register.cshtml
  Meal Ordering Restaurant/wwwroot/images/MealOrderingLogo.jpg
Labels: bug

#33 fixed image on register page on customer
  Meal Ordering Customer/Views/Account/Register.cshtml
Labels: bug
